### ISSUE TITLE
when to release train code

### ISSUE THREAD

**Issue by xiamenwcy** [m-tofighi/SP-CNN#1]
hi, I want to know when to release training code. Is there a schedule?Thank you !

**Comment by m-tofighi** [comment]
Hi Caiyong,

We are planning to release the training codes after our paper got through. But very recently I published the trained models. Now you can download it from github as well. 

With test code and trained model you can do the testing. For assessment we used the Matlab codes provided by Sirinukunwattana et al.

Thanks for your interest,
